


def get_dict_MENU_ITEMS():
    return [
    {
        "id": "burger",
        "name": "Smoky House Burger",
        "price": 14,
        "store": "Urban Bites Kitchen",
        "department": "Food",
        "category": "Best Seller",
        "description": "Grilled beef, cheddar, caramelized onions, and signature sauce.",
        "ingredients": {"Bun": 1, "Beef Patty": 1, "Cheddar": 1, "Onions": 2, "Sauce": 1},
        "ingredient_prices": {"Bun": 0.75, "Beef Patty": 2.5, "Cheddar": 0.8, "Onions": 0.35, "Sauce": 0.25},
        "image": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "pizza",
        "name": "Fire Oven Pizza",
        "price": 18,
        "store": "Urban Bites Kitchen",
        "department": "Food",
        "category": "Chef Pick",
        "description": "Stone-baked crust with basil, mozzarella, and roasted tomato.",
        "ingredients": {"Dough": 1, "Mozzarella": 2, "Basil": 4, "Tomato": 3},
        "ingredient_prices": {"Dough": 1.2, "Mozzarella": 0.9, "Basil": 0.2, "Tomato": 0.35},
        "image": "https://images.unsplash.com/photo-1548365328-9f547fb0953c?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "bowl",
        "name": "Green Power Bowl",
        "price": 13,
        "store": "Urban Bites Kitchen",
        "department": "Food",
        "category": "Fresh",
        "description": "Quinoa, avocado, crispy chickpeas, cucumber, and lime dressing.",
        "ingredients": {"Quinoa": 4, "Avocado": 2, "Chickpeas": 2, "Cucumber": 3},
        "ingredient_prices": {"Quinoa": 0.45, "Avocado": 1.1, "Chickpeas": 0.5, "Cucumber": 0.3},
        "image": "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "tacos",
        "name": "Street Tacos",
        "price": 12,
        "store": "Urban Bites Kitchen",
        "department": "Food",
        "category": "Fast Favorite",
        "description": "Three loaded tacos with salsa verde and pickled onions.",
        "ingredients": {"Tortillas": 3, "Beef": 2, "Onions": 2, "Salsa": 1},
        "ingredient_prices": {"Tortillas": 0.5, "Beef": 1.5, "Onions": 0.3, "Salsa": 0.25},
        "image": "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "burrito",
        "name": "Loaded Burrito",
        "price": 15,
        "store": "Urban Bites Kitchen",
        "department": "Food",
        "category": "Build It",
        "description": "A burrito with adjustable rice, beans, chicken, cheese, and salsa.",
        "ingredients": {"Rice": 5, "Beans": 3, "Chicken": 2, "Cheese": 2, "Salsa": 1},
        "ingredient_prices": {"Rice": 0.4, "Beans": 0.55, "Chicken": 1.6, "Cheese": 0.85, "Salsa": 0.3},
        "image": "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "margherita",
        "name": "Margherita Classic",
        "price": 16,
        "store": "Slice House Pizza",
        "department": "Food",
        "category": "Pizza House",
        "description": "Wood-fired pizza with tomato sauce, mozzarella, and basil.",
        "ingredients": {"Dough": 1, "Mozzarella": 2, "Basil": 4, "Sauce": 2},
        "ingredient_prices": {"Dough": 1.2, "Mozzarella": 0.9, "Basil": 0.2, "Sauce": 0.35},
        "image": "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "pepperoni",
        "name": "Pepperoni Heat",
        "price": 19,
        "store": "Slice House Pizza",
        "department": "Food",
        "category": "Pizza House",
        "description": "Pepperoni, chili oil, mozzarella, and roasted garlic.",
        "ingredients": {"Dough": 1, "Pepperoni": 5, "Mozzarella": 2, "Garlic": 2},
        "ingredient_prices": {"Dough": 1.2, "Pepperoni": 0.75, "Mozzarella": 0.9, "Garlic": 0.25},
        "image": "https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "veggie-pie",
        "name": "Garden Veggie Pie",
        "price": 17,
        "store": "Slice House Pizza",
        "department": "Food",
        "category": "Pizza House",
        "description": "Bell peppers, olives, mushrooms, onions, and provolone.",
        "ingredients": {"Peppers": 3, "Olives": 2, "Mushrooms": 3, "Onions": 2},
        "ingredient_prices": {"Peppers": 0.35, "Olives": 0.4, "Mushrooms": 0.45, "Onions": 0.3},
        "image": "https://images.unsplash.com/photo-1594007654729-407eedc4be65?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "mango-smoothie",
        "name": "Mango Smoothie",
        "price": 7,
        "store": "Fresh Sip Beverages",
        "department": "Food",
        "category": "Beverage",
        "description": "Cold mango smoothie blended with yogurt and ice.",
        "ingredients": {"Mango": 3, "Yogurt": 1, "Ice": 2, "Honey": 1},
        "ingredient_prices": {"Mango": 0.8, "Yogurt": 0.6, "Ice": 0.1, "Honey": 0.25},
        "image": "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "iced-coffee",
        "name": "Iced Coffee",
        "price": 6,
        "store": "Fresh Sip Beverages",
        "department": "Food",
        "category": "Beverage",
        "description": "Chilled coffee with milk, syrup, and extra ice options.",
        "ingredients": {"Coffee": 2, "Milk": 1, "Ice": 2, "Vanilla": 1},
        "ingredient_prices": {"Coffee": 0.9, "Milk": 0.45, "Ice": 0.1, "Vanilla": 0.3},
        "image": "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "berry-lemonade",
        "name": "Berry Lemonade",
        "price": 5,
        "store": "Fresh Sip Beverages",
        "department": "Food",
        "category": "Beverage",
        "description": "Fresh lemonade with mixed berries and adjustable sweetness.",
        "ingredients": {"Lemon": 2, "Berries": 2, "Sugar": 1, "Ice": 2},
        "ingredient_prices": {"Lemon": 0.35, "Berries": 0.6, "Sugar": 0.15, "Ice": 0.1},
        "image": "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "matcha-latte",
        "name": "Matcha Latte",
        "price": 8,
        "store": "Fresh Sip Beverages",
        "department": "Food",
        "category": "Beverage",
        "description": "Creamy matcha drink with milk, foam, and sweetener controls.",
        "ingredients": {"Matcha": 2, "Milk": 1, "Foam": 1, "Sweetener": 1},
        "ingredient_prices": {"Matcha": 1.0, "Milk": 0.45, "Foam": 0.25, "Sweetener": 0.2},
        "image": "https://images.unsplash.com/photo-1515823662972-da6a2e4d3002?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "fresh-tomatoes",
        "name": "Fresh Tomatoes",
        "price": 4,
        "store": "Harvest Market",
        "department": "Food",
        "category": "Groceries",
        "description": "Ripe red tomatoes for salads, sauces, and home cooking.",
        "image": "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "yellow-onions",
        "name": "Yellow Onions",
        "price": 3,
        "store": "Harvest Market",
        "department": "Food",
        "category": "Groceries",
        "description": "Kitchen onions for soups, stews, rice, and everyday meals.",
        "image": "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "spice-mix",
        "name": "House Spice Mix",
        "price": 6,
        "store": "Harvest Market",
        "department": "Food",
        "category": "Groceries",
        "description": "A versatile seasoning blend for meats, vegetables, and grains.",
        "image": "https://images.unsplash.com/photo-1532336414038-cf19250c5757?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "olive-oil",
        "name": "Cooking Olive Oil",
        "price": 10,
        "store": "Harvest Market",
        "department": "Food",
        "category": "Groceries",
        "description": "Everyday olive oil for sauteing, roasting, and salad dressing.",
        "image": "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "green-vegetables",
        "name": "Mixed Vegetables",
        "price": 7,
        "store": "Harvest Market",
        "department": "Food",
        "category": "Groceries",
        "description": "A fresh mix of greens and seasonal vegetables for cooking.",
        "image": "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "dry-beans",
        "name": "Dry Beans Bag",
        "price": 5,
        "store": "Harvest Market",
        "department": "Food",
        "category": "Groceries",
        "description": "Pantry beans ready for soups, burritos, bowls, and chili.",
        "image": "https://images.unsplash.com/photo-1515543904379-3d757afe72e3?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "sweet-corn",
        "name": "Sweet Corn",
        "price": 4,
        "store": "Harvest Market",
        "department": "Food",
        "category": "Groceries",
        "description": "Fresh sweet corn for salads, sides, and skillet dishes.",
        "image": "https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "cafeteria-coffee",
        "name": "Fresh Brew Coffee",
        "price": 4,
        "store": "Sunrise Cafeteria",
        "department": "Food",
        "category": "Cafeteria",
        "description": "Hot brewed coffee served smooth and ready for the morning rush.",
        "image": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "hot-chocolate",
        "name": "Hot Chocolate",
        "price": 5,
        "store": "Sunrise Cafeteria",
        "department": "Food",
        "category": "Cafeteria",
        "description": "Rich hot chocolate topped with a creamy, comforting finish.",
        "image": "https://images.unsplash.com/photo-1517578239113-b03992dcdd25?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "oatmeal-bowl",
        "name": "Warm Oatmeal Bowl",
        "price": 7,
        "store": "Sunrise Cafeteria",
        "department": "Food",
        "category": "Breakfast",
        "description": "Hearty oatmeal bowl for breakfast with a soft, homestyle texture.",
        "image": "https://images.unsplash.com/photo-1517673400267-0251440c45dc?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "scrambled-eggs",
        "name": "Scrambled Eggs",
        "price": 8,
        "store": "Sunrise Cafeteria",
        "department": "Food",
        "category": "Breakfast",
        "description": "Fluffy scrambled eggs cooked fresh for a quick cafeteria breakfast.",
        "options": {
            "Bread": {
                "default": "White Toast",
                "choices": {"White Toast": 0, "Wheat Toast": 0.5, "Brioche": 1.0},
            },
            "Egg Type": {
                "default": "Regular Eggs",
                "choices": {"Regular Eggs": 0, "Egg Whites": 1.0, "Brown Farm Eggs": 1.5},
            },
        },
        "image": "https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "cooked-eggs",
        "name": "Cooked Eggs Plate",
        "price": 8,
        "store": "Sunrise Cafeteria",
        "department": "Food",
        "category": "Breakfast",
        "description": "Simple cooked eggs plate served hot and ready for breakfast orders.",
        "image": "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "fried-eggs",
        "name": "Fried Eggs",
        "price": 8,
        "store": "Sunrise Cafeteria",
        "department": "Food",
        "category": "Breakfast",
        "description": "Classic fried eggs with crisp edges and a tender center.",
        "options": {
            "Bread": {
                "default": "White Toast",
                "choices": {"White Toast": 0, "Wheat Toast": 0.5, "Brioche": 1.0},
            },
            "Egg Type": {
                "default": "Sunny Side Up",
                "choices": {"Sunny Side Up": 0, "Over Easy": 0.5, "Over Hard": 0.5, "Brown Farm Eggs": 1.5},
            },
        },
        "image": "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "pain-relief",
        "name": "Pain Relief Tablets",
        "price": 11,
        "store": "CarePlus Pharmacy",
        "department": "Pharmacy",
        "category": "Pain Care",
        "description": "Fast-acting tablets for headaches, fever, and body aches.",
        "image": "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "vitamin-c",
        "name": "Vitamin C Gummies",
        "price": 14,
        "store": "CarePlus Pharmacy",
        "department": "Pharmacy",
        "category": "Wellness",
        "description": "Daily immune support gummies with orange flavor.",
        "image": "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "cough-syrup",
        "name": "Cough Relief Syrup",
        "price": 13,
        "store": "CarePlus Pharmacy",
        "department": "Pharmacy",
        "category": "Cold Relief",
        "description": "Soothing syrup for cough and throat irritation.",
        "image": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "first-aid",
        "name": "First Aid Kit",
        "price": 22,
        "store": "CarePlus Pharmacy",
        "department": "Pharmacy",
        "category": "Essentials",
        "description": "Compact home kit with bandages, wipes, gauze, and tape.",
        "image": "https://images.unsplash.com/photo-1603398938378-e54eab446dde?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "craft-lager",
        "name": "Craft Lager Pack",
        "price": 18,
        "store": "Night Owl Spirits",
        "department": "Alcohol",
        "category": "Beer",
        "description": "Six-pack of crisp craft lager with a smooth finish.",
        "image": "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "red-wine",
        "name": "Red Wine Bottle",
        "price": 24,
        "store": "Night Owl Spirits",
        "department": "Alcohol",
        "category": "Wine",
        "description": "Medium-bodied red wine with berry notes and soft tannins.",
        "image": "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "whiskey",
        "name": "Reserve Whiskey",
        "price": 42,
        "store": "Night Owl Spirits",
        "department": "Alcohol",
        "category": "Spirits",
        "description": "Oak-aged whiskey with caramel, vanilla, and spice notes.",
        "image": "https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=900&q=80",
    },
    {
        "id": "hard-seltzer",
        "name": "Berry Hard Seltzer",
        "price": 16,
        "store": "Night Owl Spirits",
        "department": "Alcohol",
        "category": "Ready To Drink",
        "description": "Refreshing sparkling seltzer with berry flavor.",
        "image": "https://images.unsplash.com/photo-1609951651556-5334e2706168?auto=format&fit=crop&w=900&q=80",
    },
]


def get_dict_RENTAL_LISTINGS(): return [
    {
        "id": "downtown-loft",
        "name": "Downtown Loft",
        "price_label": "$1,850 / month",
        "description": "Bright one-bedroom loft with open kitchen, balcony, and quick access to restaurants and transit.",
        "image": "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
        "map_url": "https://maps.google.com/maps?q=Downtown%20Miami&t=&z=13&ie=UTF8&iwloc=&output=embed",
    },
    {
        "id": "garden-apartment",
        "name": "Garden Apartment",
        "price_label": "$1,420 / month",
        "description": "Cozy rental with a green courtyard view, two bedrooms, and a calm residential setting.",
        "image": "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
        "map_url": "https://maps.google.com/maps?q=Brooklyn%20NY&t=&z=13&ie=UTF8&iwloc=&output=embed",
    },
    {
        "id": "city-studio",
        "name": "City Studio",
        "price_label": "$1,260 / month",
        "description": "Compact modern studio with smart storage, full bath, and walkable access to shops and nightlife.",
        "image": "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
        "map_url": "https://maps.google.com/maps?q=Queens%20NY&t=&z=13&ie=UTF8&iwloc=&output=embed",
    },
]










